# Specifies the Docker Compose file format version. Version 3.8 is a recent, stable version.
version: "3.8"

# Defines the services (containers) that make up your application.
services:
    # The name of our service (can be anything you like).
    app:
        # Tells Docker Compose to build the image from the Dockerfile in the current directory.
        build: .
        # Sets a name for the container for easier identification.
        container_name: express_app
        # Loads environment variables from a .env file in the same directory.
        env_file:
            - .env
        # Port mapping. This maps port 8500 on the host machine to port 3000 in the container.
        # The container exposes port 3000 (as defined in your Dockerfile).
        ports:
            - "8500:4000"
        # Restarts the container automatically if it stops.
        # 'unless-stopped' means it will restart unless you manually stop it.
        restart: unless-stopped
